# Generated by Django 3.2.6 on 2021-11-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('head1', models.CharField(max_length=100)),
                ('desc1', models.CharField(max_length=5000)),
                ('head2', models.CharField(max_length=100)),
                ('desc2', models.CharField(max_length=5000)),
                ('head3', models.CharField(max_length=100)),
                ('desc3', models.CharField(max_length=5000)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
    ]
